baseURL = "https://anecdotalthoughts.com"
languageCode = "en-us"
title = "Anecdotal Thoughts"
theme = "lines"
disableKinds = ["section", "categories"]
disqusShortname = ""
pygmentsCodeFences = true
pygmentsUseClasses = false
paginate = 999
minify = true


[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[Author]
  name = "Anas Mohamed"

[params]
  description = "Anecdotal Thoughts"
  author = "Anas Mohamed"
  copyright = "Anas Mohamed"
  logo = "favicon.ico"

[frontmatter]
  date  = [":filename", ":default"]
  author = "Anas Mohamed"
  github = "https://github.com/amohamed11"
  sitename = "Anas Mohamed"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
  [markup.highlight]
    style = 'fruity'

[permalinks]
  posts = "/:filename"
  notes = "notes/:filename"
  pages = "/:slug"
  photos = "/:year/:month/:day/:filename"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "~/posts"
    url        = "/"
    weight     = -110

  [[menu.main]]
    identifier = "notes"
    name       = "~/notes"
    url        = "/notes"
    weight     = -80

  [[menu.main]]
    identifier = "about"
    name       = "~/about"
    url        = "/about"

  [[menu.main]]
    identifier = "rss"
    name       = "~/rss"
    url        = "/atom.xml"
