baseURL = "https://anecdotalthoughts.com"
title = "anecdotal thoughts"
theme = "lines"
pygmentsCodeFences = true
pygmentsUseClasses = false
paginate = 999
ignoreLogs = ['warning-goldmark-raw-html']


[minify]
  minifyOutput = true

[taxonomies]
  tag = "tags"

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true


[params]
  description = "anecdotal thoughts"
  subtitle = "a log of cognitive hearsay"
  copyright = "Anas Mohamed"
  logo = "favicon.ico"
  [params.author]
    name = "Anas Mohamed"

[frontmatter]
  date  = [":filename", ":default"]
  author = "Anas Mohamed"
  github = "https://github.com/amohamed11"
  sitename = "Anas Mohamed"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
  [markup.highlight]
    style = 'fruity'

[permalinks]
  posts = "/posts/:filename"
  notes = "/notes/:filename"
  pages = "/:slug"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[menu]
  [[menu.main]]
    identifier = "posts"
    name       = "~/posts"
    url        = "/"
    weight     = -110
    
  [[menu.main]]
    identifier = "now"
    name       = "~/now"
    url        = "/now"
    weight     = -80

  [[menu.main]]
    identifier = "notes"
    name       = "~/notes"
    url        = "/notes"
    weight     = -50

  [[menu.main]]
    identifier = "about"
    name       = "~/about"
    url        = "/about"

[caches]
  [caches.images]
    dir = ":cacheDir/images"